-- 재고 테이블
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    NO NUMBER,
    PRODUCT_ID VARCHAR2(15),
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER DEFAULT 0 NOT NULL,
    DESCRIPTION VARCHAR2(15),
    STOCK NUMBER NOT NULL,
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PRODUCT_NO PRIMARY KEY (NO)
);

-- 재고 데이터 INSERT 쿼리
INSERT INTO PRODUCT 
VALUES(SEQ_NO.NEXTVAL, 'pid_ss4', '갤럭시북', 2890000, '울트라 4', 15, SYSDATE);
INSERT INTO PRODUCT 
VALUES(SEQ_NO.NEXTVAL, 'pid_ap16', '맥북', 3490000, '프로 16', 15, SYSDATE);
INSERT INTO PRODUCT 
VALUES(SEQ_NO.NEXTVAL, 'pid_lg16', '그램', 2490000, '프로 16', 15, SYSDATE);

-- 재고 시퀀스
DROP SEQUENCE SEQ_NO;
CREATE SEQUENCE SEQ_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 재고 입,출고 기록 테이블
DROP TABLE BACK_PRODUCT;
CREATE TABLE BACK_PRODUCT(
    NO NUMBER,
    B_NO NUMBER,
    AMOUNT NUMBER DEFAULT 0,
    STATUS VARCHAR2(10) CHECK (STATUS IN ('입고','출고')),
    B_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BACK_PRODUCT_B_NO PRIMARY KEY (B_NO),
    CONSTRAINT FK_BACK_PRODUCT_NO FOREIGN KEY (NO) REFERENCES PRODUCT (NO)
);

-- 입,출고 시퀀스
DROP SEQUENCE SEQ_B_NO;
CREATE SEQUENCE SEQ_B_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 트리거
DROP TRIGGER TRG_PRODUCT;
CREATE OR REPLACE TRIGGER TRG_PRODUCT
AFTER INSERT ON BACK_PRODUCT
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = '입고' THEN
        UPDATE PRODUCT SET STOCK = STOCK + :NEW.AMOUNT 
        WHERE NO = :NEW.NO;
    ELSIF : NEW.STATUS = '출고' THEN
        UPDATE PRODUCT SET STOCK = STOCK - :NEW.AMOUNT 
        WHERE NO = :NEW.NO AND STOCK >= : NEW.AMOUNT;
    END IF;
END;
/

-- 입, 출고 명령 쿼리문
INSERT INTO BACK_PRODUCT (B_NO, NO, B_DATE, AMOUNT, STATUS)
VALUES (SEQ_B_NO.NEXTVAL, 1, SYSDATE, 5, '입고');
INSERT INTO BACK_PRODUCT (B_NO, NO, B_DATE, AMOUNT, STATUS)
VALUES (SEQ_B_NO.NEXTVAL, 1, SYSDATE, 3, '출고');

-- 확인 쿼리
SELECT * FROM PRODUCT;
SELECT * FROM BACK_PRODUCT;
SELECT * FROM USER_SEQUENCES;

COMMIT;
ROLLBACK;